LISP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('investment_manager.urls')),
    path('', include('django_dyn_dt.urls')),
]

investment_manager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('about/', views.about, name='about'),
    path('register/', views.register_user, name='register'),
    path('client/', views.all_client_data, name='client'),
    path('contribution/', views.all_contribution_data, name='client_contribution'),
    path('investment/', views.all_investment_data, name='client_investment'),
    path('individual/client/<int:pk>/', views.individual_client_data, name='individual_client'),
    path('individual/contributions/<int:pk>/', views.individual_contribution_data, name='individual_contributions'),
    path('individual/investments/<int:pk>/', views.individual_investment_data, name='individual_investments'),
    path('create_client/', views.create_client, name='create_client'),
    path('update_records/', views.update_records, name='update_records'),
    path('individual/<int:client_id>/create_contribution/', views.create_contribution, name='create_contribution'),
    path('individual/<int:client_id>/create_investment', views.create_investment, name='create_investment'),
]

investment_manager/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from dateutil.relativedelta import relativedelta
from datetime import date
from decimal import Decimal


# Create your models here.
class Client(models.Model):

    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)
    city = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    client_nrc = models.CharField(
        max_length=11,
        validators=[
            RegexValidator(
                regex=r'^\d{6}/\d{2}/\d$',
                message='NRC must be in the format 123456/78/9'
            )
        ],
        unique=True
    )
    date_of_joining = models.DateField() 
    risk_level = models.CharField(
        max_length=10,
        choices=[
            ('low', 'Low'), 
            ('medium', 'Medium'), 
            ('high', 'High')
        ]
    )
    contribution_type = models.CharField(
        max_length=50,
        choices=[
            ('lump_sum', 'Lump Sum'), 
            ('regular_contribution', 'Regular Contribution')
        ]
    )
    contribution_frequency = models.CharField(
        max_length=50,
        choices=[
            ('monthly', 'Monthly'), 
            ('quarterly', 'Quarterly'), 
            ('semi-annual', 'Semi-Annual'), 
            ('annual', 'Annual'), 
            ('once_off', 'Once-Off')
        ]
    )
    financial_goal = models.CharField(
        max_length=50,
        choices=[
            ('education', 'Education'), 
            ('retirement', 'Retirement'), 
            ('emergency_fund', 'Emergency Fund'), 
            ('home_ownership', 'Home Ownership'), 
            ('business', 'Business')
        ]
    )
    target_amount = models.DecimalField(max_digits=12, decimal_places=2)
    expected_contribution = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(
        max_length=3,
        choices=[('usd', 'USD'), ('zmw', 'ZMW')]
    )
    manager = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def format_target(self):
        return f"{self.target_amount:,.2f}"
    
    def format_contribution(self):
        return f"{self.expected_contribution:,.2f}"

    def get_manager_full_name(self):
        return f"{self.manager.first_name} {self.manager.last_name}"

    def __str__(self):
        return self.full_name

    def save(self, *args, **kwargs):
        if self.contribution_type == 'lump_sum':
            self.contribution_frequency = 'once_off'
        super(Client, self).save(*args, **kwargs)

    def total_contributions(self):
        return self.contribution_set.aggregate(total=models.Sum('investable_amount'))['total'] or 0
    
    def total_investments(self):
        return self.investment_set.aggregate(total=models.Sum('investment_amount'))['total'] or 0
    
    def amount_left_for_investment(self):
        return self.total_contributions() - self.total_investments()


class Contribution(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateField()
    contribution_amount = models.DecimalField(max_digits=12, decimal_places=2)
    payment_method = models.CharField(
        max_length=50, 
        choices=[
            ('cash', 'Cash'), 
            ('ddacc', 'DDACC'), 
            ('mobile_money', 'Mobile Money'), 
            ('bank_transfer', 'Bank Transfer'), 
            ('cheque', 'Cheque')
        ]
    )
    fee_rate_percentage = models.DecimalField(max_digits=5, decimal_places=3, null=True, blank=True, default=Decimal('3.000'))
    fees = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    investable_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    manager = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    description = models.TextField(null=True, blank=True)  # Optional field for additional context

    def get_manager_full_name(self):
        return f"{self.manager.first_name} {self.manager.last_name}"

    def save(self, *args, **kwargs):
        self.fees = self.contribution_amount * Decimal(self.fee_rate_percentage) / 100
        self.investable_amount = self.contribution_amount - self.fees
        super(Contribution, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.client.currency.upper()} {self.contribution_amount:,.2f} Received On: {self.date:%d/%m/%Y}"


class Investment(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    investment_duration = models.IntegerField()
    start_date = models.DateField()
    maturity_date = models.DateField(null=True, blank=True)
    investment_type = models.CharField(
        max_length=50,
        choices=[
            ('fd', 'Fixed Deposit'), 
            ('bond', 'Government Bond'), 
            ('t_bill', 'Treasury Bill'), 
            ('abc_bf', 'ABC Balanced Fund'),
            ('abc_ef', 'ABC Equity Fund'),
            ('abc_mmf', 'ABC Money Market Fund'),
            ('abc_usdf', 'ABC USD Fund'),
            ('abc_usd_hyf', 'ABC USD High-Yield Fund'),
            ('abc_zmw_hyf', 'ABC ZMW High-Yield Fund'),
            ('mpile_bf', 'Mpile Balanced Fund'),
            ('mpile_gf', 'Mpile Gratuity Fund'),
            ('mpile_hydf', 'Mpile High-Yield Debt Fund'),
            ('mpile_lef', 'Mpile Local Equity Fund'),
            ('mpile_mmf', 'Mpile Money Market Fund'),
            ('mpile_osef', 'Mpile Offshore Equity Fund'),
            ('mpile_pf', 'Mpile Property Fund'),
        ]
    )
    investment_amount = models.DecimalField(max_digits=10, decimal_places=2)
    expected_annual_growth_rate_percentage = models.DecimalField(max_digits=5, decimal_places=3)
    expected_current_value = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    description = models.TextField(null=True, blank=True)  # Optional field for additional context
    status = models.CharField(max_length=20, choices=[('active', 'Active'), ('completed', 'Completed')], default='active')

    def get_manager_full_name(self):
        return f"{self.manager.first_name} {self.manager.last_name}"

    def clean(self):
        if self.client.amount_left_for_investment() < self.investment_amount:
            raise ValidationError(
                f"The investment amount of {self.client.currency.upper()} {self.investment_amount:.2f} exceeds the amount left for investment for the client ({self.client.currency.upper()} {self.client.amount_left_for_investment():.2f})"
            )

    def save(self, *args, validate=True, **kwargs):
        if not self.maturity_date:
            self.maturity_date = self.start_date + relativedelta(months=self.investment_duration)

        if validate:
            self.full_clean()  # Validate the model instance

        # Calculate the expected current value based on the elapsed time
        if date.today() > self.maturity_date:
            days_elapsed = (self.maturity_date - self.start_date).days
        else:
            days_elapsed = (date.today() - self.start_date).days
        years_elapsed = Decimal(days_elapsed) / Decimal('365.25')  # Approximate number of days in a year including leap years
        self.expected_current_value = self.investment_amount * (Decimal('1') + self.expected_annual_growth_rate_percentage / 100) ** years_elapsed

        # Update status based on maturity date
        if date.today() > self.maturity_date:
            self.status = 'completed'
        else:
            self.status = 'active'

        super(Investment, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.client.currency.upper()} {self.investment_amount:.2f} Invested On: {self.start_date:%d/%m/%Y}"

investment_manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Client, Investment, Contribution
from .forms import SignUpForm, CreateClientForm, CreateContributionForm, CreateInvestmentForm
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Sum

@login_required
def home(request):
    
    return render(request, 'investment_manager/home.html', {})

def login_user(request):
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "You have successfully logged in. Welcome back!")
            return redirect('home')
        else:
            messages.error(request, "Invalid Username or Password! Please try again.")
            return render(request, 'investment_manager/login.html')
    else:
        return render(request, 'investment_manager/login.html')

def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out!")
    return redirect('login')


def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You Have Successfully Registered. Welcome to LISP!")
            return redirect('home')
    else:
        form = SignUpForm()
        return render(request, 'investment_manager/register.html', {'form': form})
    
    return render(request, 'investment_manager/register.html', {'form': form})


def all_client_data(request):
    if request.user.is_authenticated:
        # look up client data
        context = {
        'clients': Client.objects.all()
    }
        return render(request, 'investment_manager/clients.html', context)
    else:
        messages.success(request, 'You Must Be Logged in to View Client Records!')
        return redirect('login')
    

def all_contribution_data(request):
    if request.user.is_authenticated:
        # client = get_object_or_404(Client)
        contributions = Contribution.objects.all()
        context = {
            'contributions': contributions 
        }
        return render(request, 'investment_manager/all_client_contributions.html', context)


def all_investment_data(request):
    if request.user.is_authenticated:
        # Example of fetching investments for a specific client
        # client = get_object_or_404(Client, pk=request.GET.get('client_id'))
        investments = Investment.objects.all()
        context = {
            'investments': investments
        }
        return render(request, 'investment_manager/all_client_investments.html', context)
    
@login_required
def individual_client_data(request, pk):
    client_data = get_object_or_404(Client, pk=pk)
    return render(request, 'investment_manager/individual_client.html', {'client_data': client_data})


@login_required
def individual_contribution_data(request, pk):
    client = Client.objects.get(id=pk)
    contributions = Contribution.objects.filter(client=client)
    total_contributions = contributions.count()
    total_amount_contributed = contributions.aggregate(Sum('contribution_amount'))['contribution_amount__sum'] or 0
    total_fees = contributions.aggregate(Sum('fees'))['fees__sum'] or 0

    context = {
        'client_data': client,
        'contributions': contributions,
        'total_contributions': total_contributions,
        'total_amount_contributed': total_amount_contributed,
        'total_fees': total_fees,
    }
    return render(request, 'investment_manager/individual_contributions.html', context)


@login_required
def individual_investment_data(request, pk):
    client = get_object_or_404(Client, id=pk)
    investments = Investment.objects.filter(client=client)
    total_investments = investments.count()
    total_amount_invested = investments.aggregate(Sum('investment_amount'))['investment_amount__sum'] or 0

    context = {
        'client_data': client,
        'investments': investments,
        'total_investments': total_investments,
        'total_amount_invested': total_amount_invested,
    }
    return render(request, 'investment_manager/individual_investments.html', context)



@login_required
def create_client(request):
    if request.method == 'POST':
        form = CreateClientForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.manager = request.user
            client.save()
            messages.success(request, "Client Added Successfully!")
            return HttpResponseRedirect(reverse('create_client'))  # Redirect to the same view
    else:
        form = CreateClientForm()
    return render(request, 'investment_manager/create_client.html', {'form': form})


@login_required
def create_contribution(request, client_id):
    if request.method == 'POST':
        form = CreateContributionForm(request.POST, client_id=client_id)
        if form.is_valid():
            contribution = form.save(commit=False)
            contribution.manager = request.user
            contribution.save()
            messages.success(request, "Contribution Added Successfully!")
            return HttpResponseRedirect(reverse('create_contribution', args=[client_id]))  # Redirect to the same view
    else:
        form = CreateContributionForm(client_id=client_id)
    return render(request, 'investment_manager/create_contribution.html', {'form': form})


@login_required
def create_investment(request, client_id):
    if request.method == 'POST':
        form = CreateInvestmentForm(request.POST, client_id=client_id)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.manager = request.user
            investment.save()
            messages.success(request, "Investment Added Successfully!")
            return HttpResponseRedirect(reverse('create_investment', args=[client_id]))  # Redirect to the same view
    else:
        form = CreateInvestmentForm(client_id=client_id)
    return render(request, 'investment_manager/create_investment.html', {'form': form})


def about(request):
    return render(
        request,
        'investment_manager/about.html',
        {'title': 'About'}
    )

@login_required
def update_records(request):
    if request.method == 'POST':
        investments = Investment.objects.all()
        for investment in investments:
            try:
                investment.save(validate=False)  # Bypass validation
            except ValidationError as e:
                messages.error(request, f"Failed to update investment {investment.id}: {e}")
        messages.success(request, "All valid Investment Records updated")
    return render(request, 'investment_manager/update_records.html', {})

investment_manager/templates/investment_manager/all_client_contributions.html
<div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top">
        <!-- <caption><h4>List of Contributions</h4></caption> -->
        <thead class="table-primary">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Client Name</th>
            <th scope="col">Date Received</th>
            <th scope="col">Amount Received</th>
            <th scope="col">Payment Method</th>
            <th scope="col">Fees</th>
            <th scope="col">Investable Amount</th>
            <th scope="col">Manager</th>
        </tr>
        </thead>
        <tbody>
            {% if contributions %}
                {% for contribution in contributions %}
                    <tr>
                        <td>{{ contribution.id }}</td>
                        <td>{{ contribution.client }}</td>
                        <td>{{ contribution.date }}</td>
                        <td>{{ contribution.contribution_amount }}</td>
                        <td>{{ contribution.get_payment_method_display }}</td>
                        <td>{{ contribution.fees }}</td>
                        <td>{{ contribution.investable_amount }}</td>
                        <td>{{ contribution.get_manager_full_name }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
</div>

investment_manager/templates/investment_manager/all_client_investments.html
<div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top">
        <!-- <caption><h4>List of Investments</h4></caption> -->
        <thead class="table-primary">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Client</th>
            <th scope="col">Investment Vehicle</th>
            <th scope="col">Invested Amount</th>
            <th scope="col">Start Date</th>
            <th scope="col">Maturity Date</th>
            <th scope="col">Expected Growth Rate</th>
            <th scope="col">Expected Current Value</th>
            <th scope="col">Manager</th>
            <th scope="col">Status</th>
        </tr>
        </thead>
        <tbody>
            {% if investments %}
                {% for investment in investments %}
                    <tr>
                        <td>{{ investment.id }}</td>
                        <td>{{ investment.client }}</td>
                        <td>{{ investment.get_investment_type_display }}</td>
                        <td>{{ investment.investment_amount }}</td>
                        <td>{{ investment.start_date }}</td>
                        <td>{{ investment.maturity_date }}</td>
                        <td>{{ investment.expected_annual_growth_rate_percentage }}</td>
                        <td>{{ investment.expected_current_value }}</td>
                        <td>{{ investment.get_manager_full_name }}</td>
                        <td>{{ investment.get_status_display }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
</div>

investment_manager/templates/investment_manager/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>LISP Application</title>
  </head>
  <body>
    {% include 'investment_manager/navbar.html' %}
    <div class="container-fluid">
        <br/>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

investment_manager/templates/investment_manager/clients.html
<div>
    <table class="table table-striped table-bordered table-sm table-hover caption-top">
        <caption><a href="{% url 'create_client' %}" class="btn btn-primary">Add Client</a></caption>

        <thead class="table-primary">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Client Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">NRC</th>
            <th scope="col">Risk Level</th>
            <th scope="col">Financial Goal</th>
            <th scope="col">Amount</th>
            <th scope="col">Frequency</th>
            <th scope="col">Final Target</th>
            <th scope="col">Currency</th>
            <th scope="col">Client</th>
            <th scope="col">Contrib.</th>
            <th scope="col">Invest.</th>
            
        </tr>
        </thead>
        <tbody>
            {% if clients %}
                {% for client in clients %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>{{ client.full_name }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.phone }}</td>
                        <td>{{ client.client_nrc }}</td>
                        <td>{{ client.get_risk_level_display }}</td>
                        <td>{{ client.financial_goal.capitalize }}</td>
                        <td>{{ client.expected_contribution }}</td>
                        <td>{{ client.get_contribution_frequency_display }}</td>
                        <td>{{ client.target_amount }}</td>
                        <td>{{ client.currency.upper }}</td>
                        <td><a href="{% url 'individual_client' client.id %}">View</a></td>
                        <td><a href="{% url 'individual_contributions' client.id %}">View</a></td>
                        <td><a href="{% url 'individual_investments' client.id %}">View</a></td>
                        
                    </tr>
                    {% endfor %}
            {% endif %}
        </tbody>
    </table>
</div>

investment_manager/templates/investment_manager/create_client.html
{% extends "investment_manager/base.html" %}
{% block content %}
<div class="container">
<div class="card col-sm-8">
    <h5 class="card-header">Add New Client:</h5>
    <div class="card-body">
        <form method="POST" action="">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Your Form Has Errors!
                    {% for filed in form %}
                        {% if field.errors %}
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}

                </div>

            {% endif %}
            
            {{ form.as_p }}

            <br/>
            <button type="submit" class="btn btn-secondary">Add Client</button>
        </form>
    </div>
  </div><br>

  <a href="{% url 'home' %}" class="btn btn-primary">Back <</a>
</div>
{% endblock %}

investment_manager/templates/investment_manager/individual_client.html
{% extends "investment_manager/base.html" %}
{% block content %}
<div class="container">
<div class="card col-sm-8">
    <h5 class="card-header">Client Information:</h5>
    <div class="card-body">
        <table class="table">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col"></th>

              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Manager:</strong></td>
                <td>{{ client_data.get_manager_full_name }}</td>
              </tr>

              <tr>
                <td><strong>Client Full Name:</strong></td>
                <td>{{ client_data.full_name }}</td>
              </tr>

              <tr>
                <td><strong>Email Address:</strong></td>
                <td><a href="mailto:{{ client_data.email }}">{{ client_data.email }}</a></td>
              </tr>

              <tr>
                <td><strong>Phone Number:</strong></td>
                <td>{{ client_data.phone }}</td>
              </tr>

              <tr>
                <td><strong>City of Residence:</strong></td>
                <td>{{ client_data.city }}</td>
              </tr>

              <tr>
                <td><strong>Date of Birth:</strong></td>
                <td>{{ client_data.date_of_birth}}</td>
              </tr>

              <tr>
                <td><strong>National ID:</strong></td>
                <td>{{ client_data.client_nrc }}</td>
              </tr>

              <tr>
                <td><strong>Date of Joining:</strong></td>
                <td>{{ client_data.date_of_joining }}</td>
              </tr>

              <tr>
                <td><strong>Risk Tolerance:</strong></td>
                <td>{{ client_data.get_risk_level_display }}</td>
              </tr>

              <tr>
                <td><strong>Method of Contribution:</strong></td>
                <td>{{ client_data.get_contribution_type_display }}</td>
              </tr>

              <tr>
                <td><strong>Contribution Frequency:</strong></td>
                <td>{{ client_data.get_contribution_frequency_display }}</td>
              </tr>

              <tr>
                <td><strong>Client Financial Goal:</strong></td>
                <td>{{ client_data.get_financial_goal_display }}</td>
              </tr>

              <tr>
                <td><strong>Client Target Amount:</strong></td>
                <td>{{ client_data.get_currency_display }} {{ client_data.format_target }}</td>
              </tr>

              <tr>
                <td><strong>Expected {{ client_data.get_contribution_frequency_display }} Amount:</strong></td>
                <td>{{ client_data.get_currency_display }} {{ client_data.format_contribution }}</td>
              </tr>


            </tbody>
          </table>
        
          <a href="{% url 'create_contribution' client_data.id %}" class="btn btn-primary">Add Contribution</a> 
          <a href="{% url 'create_investment' client_data.id %}" class="btn btn-primary">Add Investment</a>
      
    </div>
  </div><br>

  <a href="{% url 'home' %}" class="btn btn-primary">Back <</a>
</div>
{% endblock %}

investment_manager/templates/investment_manager/individual_investments.html
{% extends "investment_manager/base.html" %}
{% block content %}
<div class="container">
    <div class="card col-sm-8">
        <h5 class="card-header">Client Investments Summary:</h5>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>Client Name:</strong></td>
                        <td>{{ client_data.full_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>Total Number of Investments:</strong></td>
                        <td>{{ total_investments }}</td>
                    </tr>
                    <tr>
                        <td><strong>Total Amount Invested:</strong></td>
                        <td>{{ total_amount_invested }}</td>
                    </tr>
                </tbody>
            </table>
            <a href="{% url 'create_investment' client_data.id %}" class="btn btn-primary">Add Investment</a>
        </div>
    </div><br>

    <div>
        <table class="table table-striped table-bordered table-sm table-hover caption-top">
            <caption>List of Investments</caption>
            <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Client</th>
                    <th scope="col">Investment Vehicle</th>
                    <th scope="col">Invested Amount</th>
                    <th scope="col">Start Date</th>
                    <th scope="col">Maturity Date</th>
                    <th scope="col">Expected Growth Rate</th>
                    <th scope="col">Expected Current Value</th>
                    <th scope="col">Manager</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% if investments %}
                    {% for investment in investments %}
                        <tr>
                            <td>{{ investment.id }}</td>
                            <td>{{ investment.client }}</td>
                            <td>{{ investment.get_investment_type_display }}</td>
                            <td>{{ investment.investment_amount }}</td>
                            <td>{{ investment.start_date }}</td>
                            <td>{{ investment.maturity_date }}</td>
                            <td>{{ investment.expected_annual_growth_rate_percentage }}</td>
                            <td>{{ investment.expected_current_value }}</td>
                            <td>{{ investment.get_manager_full_name }}</td>
                            <td>{{ investment.get_status_display }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    </div>

    <a href="{% url 'home' %}" class="btn btn-primary">Back <</a>
</div>
{% endblock %}

investment_manager/templates/investment_manager/update_records.html
{% extends "investment_manager/base.html" %}
{% block content %}
<div class="container">
<div class="card col-sm-8">
    <h5 class="card-header">Update Records:</h5>
    <div class="card-body">
        <form method="POST" action="{% url 'update_records' %}">

            {% csrf_token %}
                <p>
                    Run the update Server command at least <strong>once a week</strong> and <strong>before report generation</strong> to update expected return computations.
                </p>
            <br/>
            <button type="submit" class="btn btn-secondary">Update Records</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}